# Generated by Django 4.1.4 on 2023-02-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusphone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cusname', models.TextField()),
                ('cusemail', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menucode', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('menuname', models.TextField()),
                ('menuprice', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sellerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sellername', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField()),
                ('pickupdate', models.DateField()),
                ('cusphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcube.customer')),
                ('menucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcube.menu')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigcube.seller')),
            ],
        ),
    ]
