# Generated by Django 4.1.4 on 2023-02-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerpassword',
            field=models.CharField(default='NULL', max_length=60),
        ),
    ]
